### ISSUE TITLE
This is not an issue but hear me out

### ISSUE THREAD

**Issue by abdullaaaah** [kyonenjs/udeguchi#10]
Bro, I love you for making this! I spent an entire day scratching my head and trying to make the popular udemy downloaders like udemy-dl and udeler try to download in 1080 but they simply didn't have the functionality. I tried to code it myself but with my limited knowledge of http I could not do it, it is 6AM here and i had almost given up when I somehow found your project. Let me tell you this is the BEST udemy downloader out there. Thank you so so much for this man. I would love to be able to help you out in any way :).

**Comment by kyonenjs** [comment]
Thank you 😁
