### ISSUE TITLE
 Error  Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by ahmadsb101** [kyonenjs/udeguchi#11]
Hi
I have done exactly like readme.md but I get  "Error  Response code 403 (Forbidden)"

I have node.js v10.19.0 and npm v6.14.5 on Debian 10 x64 machine.

**Comment by kyonenjs** [comment]
Hello @ahmadsb101

Login with username and password is not available at this moment.

But you can login with cookie. Here are steps that you can follow and download with cookie:
https://github.com/kyonenjs/udeguchi#login-with-cookie--how-

**Comment by ahmadsb101** [comment]
Hi 
Tnx for your immediate reply.
I appreciate your response.
