### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by sayemsarkar123** [kyonenjs/udeguchi#3]
See this first course already have in my account https://textuploader.com/11m6y second course show me this error :(

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello, thank you for using the tool ^^.

I don't have the course that you own.

Can you send me your cookie that you used to download? Please email me at : kyonenjs @ icloud . com

Thank you ^^

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello

I already fixed problem 1 (can't find the course that you own) and updated udeguchi.

If you clone with git, please use command : `git pull` to update udeguchi
If not, please download udeguchi again.

The cookie you sent me doesn't contain the course with problem 2. Please send me email the cookie so i can fix the problem. Thank you ^^

**Comment by kyonenjs** [comment]
Please update udeguchi. Works fine for me ^^

![a](https://user-images.githubusercontent.com/52479148/62589312-10354100-b8f3-11e9-9546-36cf22db34cb.png)

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello

The tool works fine on Windows, but i have the same problem 2 with you on Linux and macOS.

I already fixed and updated udeguchi. Please update and let me know if the problem still there ^^

Tested on:

Windows:

![windows](https://user-images.githubusercontent.com/52479148/62604501-68d00280-b922-11e9-851a-53d45313ebf3.png)

Linux:

![linux](https://user-images.githubusercontent.com/52479148/62604509-6d94b680-b922-11e9-9a92-cf7e0ffc9f68.png)

macOS:

![macos](https://user-images.githubusercontent.com/52479148/62604522-72596a80-b922-11e9-920d-c0db5f435cad.png)

**Comment by sayemsarkar123** [comment]
@kyonenjs now it's work perfectly  :) Thanks you.
