### ISSUE TITLE
another problem

### ISSUE THREAD

**Issue by sayemsarkar123** [kyonenjs/udeguchi#4]
see here https://textuploader.com/11m2z cookies send your email please check

**Comment by sayemsarkar123** [comment]
@kyonenjs still getting this error.

**Comment by sayemsarkar123** [comment]
@kyonenjs here is another problem see this https://textuploader.com/11mnl and previous path problem is not solved. check your mail

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello

I already fixed problem 1 and updated udeguchi. Please update and let me know if the problem still there ^^

Tested

![a](https://user-images.githubusercontent.com/52479148/62635581-275f4780-b962-11e9-80b3-3e9ac817e0a2.png)

**Comment by sayemsarkar123** [comment]
@kyonenjs first problem fixed

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello

I already fixed problem 2 and updated udeguchi. Please update and let me know if problem still there ^^

Tested on:

Windows

![windows](https://user-images.githubusercontent.com/52479148/62644679-d3aa2980-b974-11e9-9365-2a4320ff3f0f.png)

Linux

![linux](https://user-images.githubusercontent.com/52479148/62644687-d86edd80-b974-11e9-8b9f-890cde486f0e.png)

macOS

![macos](https://user-images.githubusercontent.com/52479148/62644699-dd339180-b974-11e9-836e-814d7d1884fb.png)

**Comment by sayemsarkar123** [comment]
problem 2 fixed @kyonenjs thanks 👍
