### ISSUE TITLE
failed to download video.

### ISSUE THREAD

**Issue by sayemsarkar123** [kyonenjs/udeguchi#5]
http://prntscr.com/ox3ouu
node app.js --lang en --cookie cookie.txt https://www.udemy.com/draft/1145736/

access_token was sent your e-mail please check.

**Comment by sayemsarkar123** [comment]
sorry it's my fault.

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello

I already fixed and updated udeguchi. Please update and let me know if the problem still there ^^

![windows](https://user-images.githubusercontent.com/52479148/63644064-5fa8a900-c70a-11e9-8f24-01f6e6f63dd4.png)
