### ISSUE TITLE
Certification Error

### ISSUE THREAD

**Issue by ltfi** [kyonenjs/udeguchi#7]
![image](https://user-images.githubusercontent.com/1550317/64608698-ec728880-d3d3-11e9-8e69-df10be9135a4.png)
Is there any workaround for this issue?

**Comment by kyonenjs** [comment]
Did you try login with cookie ?
https://github.com/kyonenjs/udeguchi#login-with-cookie--how-

**Comment by ltfi** [comment]
ok, but know;
![image](https://user-images.githubusercontent.com/1550317/64610417-dbc41180-d3d7-11e9-9565-ad3d63e8bae0.png)
Where is the course name (on Udemy Page)?

**Comment by kyonenjs** [comment]
it's the course URL like this : https://www.udemy.com/adobe-photoshop-course/
and the command now is:
`node app.js -k cookie.txt https://www.udemy.com/adobe-photoshop-course/`

**Comment by ltfi** [comment]
![image](https://user-images.githubusercontent.com/1550317/64611854-0d8aa780-d3db-11e9-9c03-6c1ecb55342e.png)
I had this course and still get this.

**Comment by kyonenjs** [comment]
Can you send me your cookie to this email : kyonenjs @ icloud . com
So i can take a look and see what happen ^^

**Comment by ltfi** [comment]
Imm, sorry for this :=)
