### ISSUE TITLE
skip the file

### ISSUE THREAD

**Issue by sayemsarkar123** [kyonenjs/udeguchi#8]
https://imgur.com/hYObcs0
https://imgur.com/6K2IasB

here i'm found problem when it's download the chapter video it's skip this file where are pages file is presented. hopefully soon you are fix this issue's. sent cookies to your mail.

**Comment by sayemsarkar123** [comment]
sorry to forget add url: node app.js --lang en -k cookie.txt https://www.udemy.com/course/complete-web-development-course/

**Comment by sayemsarkar123** [comment]
if it's possiable can you add this functionality download question as html.

**Comment by kyonenjs** [comment]
@sayemsarkar123 Hello

I already fixed and updated udeguchi. Please update and let me know if the problem still there ^^

For question lectures like the one after lecture 440, some courses like javascript courses, that question lecture (quiz) maybe an online editor so it's not a simple html. I think i need more thought on it, maybe not available in near feature.

![a](https://user-images.githubusercontent.com/52479148/71310248-6d660500-2444-11ea-802e-5995147ee3ef.png)

**Comment by sayemsarkar123** [comment]
@kyonenjs it's solved, thanks.
